# -*- coding: utf-8 -*-
"""Spacy_practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJCDrKH8Dj-AFtdv1N2lwBoxbf-Afh2O

What is spaCy?

spaCy is a fast and production-ready Natural Language Processing (NLP) library in Python. It is designed for real-world applications such as chatbots, resume screening, sentiment analysis, document classification, information extraction, and recommendation systems.
Why spaCy?

✅ Very Fast

 ✅ Industrial Strength NLP

 ✅ Pre-trained Models Available

 ✅ Easy Integration with Machine Learning

 ✅ Supports Multiple Languages

```
Corporate Interview Questions

Q1: Why spaCy instead of NLTK?

NLTK	                  spaCy
Educational	            Production Ready
Slower	                Faster
More Learning Focus	    More Industry Focus
Research Oriented	      Deployment Oriented

Q2.What is NER?

Named Entity Recognition identifies:

Person
Organization
Location
Date
Money

Real Companies Using NLP Similar to spaCy Solutions
LinkedIn (resume matching)
Naukri (job recommendations)
Indeed (candidate screening)
Amazon (product review analysis)
Microsoft (language understanding)
Google (search understanding)
```


```
TASK:
-------------------------------------------------------------------
Customer Support Ticket Routing ⭐⭐⭐⭐⭐
Problem

Companies receive support tickets:

My payment failed.

Unable to login to my account.

Need refund for my order.

Need to automatically send them to the correct department.

Categories
Billing Team
Technical Team
Refund Team
Sales Team
spaCy Concepts

✅ NLP Pipeline
✅ Text Similarity
✅ Matcher
✅ Entity Recognition

Real Companies
Amazon
Flipkart
Swiggy
Zomato```
"""

!pip install spacy
!python -m spacy download en_core_web_sm

"""1. Tokenization

Breaking sentences into words.
"""

import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("I love learning NLP using spaCy")

for token in doc:
    print(token.text)

"""2. Part of Speech (POS) Tagging

Identifies noun, verb, adjective, etc.
"""

for token in doc:
    print(token.text, token.pos_)

"""3. Named Entity Recognition (NER)

Finding names, organizations, places, etc.
"""

doc = nlp("Microsoft hired John in Chennai.")

for ent in doc.ents:
    print(ent.text, ent.label_)

"""4. Lemmatization

Converts words to root form.
"""

doc = nlp("running runs ran")

for token in doc:
    print(token.text, token.lemma_)

"""5. Dependency Parsing

Identifies relationships among words.
"""

doc = nlp("Ram eats an apple")

for token in doc:
    print(token.text, token.dep_)

"""Real-Time Project: Resume Screening System

This is a very common corporate NLP project.

Problem Statement

HR receives thousands of resumes.

Manually reading each resume is:

Time-consuming
Expensive
Error-prone

We use spaCy to extract skills automatically.
"""

# John Doe

# Skills:
# Python
# Machine Learning
# SQL
# Power BI
# TensorFlow
import spacy
nlp = spacy.load("en_core_web_sm")
resume = """
John Doe

Skills:
Python
Machine Learning
SQL
Power BI
TensorFlow
"""

doc = nlp(resume)
skills_db = [
    "python",
    "machine learning",
    "sql",
    "power bi",
    "tensorflow",
    "nlp",
    "deep learning"
]
#Extract Skills
found_skills = []

resume_text = resume.lower()

for skill in skills_db:
    if skill in resume_text:
        found_skills.append(skill)

print(found_skills)

#Step 4: Calculate Match Score
job_skills = [
    "python",
    "sql",
    "machine learning",
    "nlp"
]

#Score Calculation:
matched = len(set(found_skills) & set(job_skills))
total = len(job_skills)
score = (matched / total) * 100
print(f"Resume Match Score: {score:.2f}%")

# Advanced Version
from spacy.matcher import PhraseMatcher
matcher = PhraseMatcher(nlp.vocab)
skills = ["Python", "SQL", "Machine Learning"]
patterns = [nlp(skill) for skill in skills]
matcher.add("SKILLS", patterns)
doc = nlp(resume)
matches = matcher(doc)
for match_id, start, end in matches:
    print(doc[start:end].text)